### ISSUE TITLE
Stucked in preprocessing 

### ISSUE THREAD

**Issue by cjavier98** [klamt-lab/straindesign#11]
I am tryng to compute the gene KOs for a large network, Human-GEM, but it is stucked in preprocessing.
Is this normal?

Strain design computation progress:
Preparing strain design computation.
Using gurobi for solving LPs during preprocessing.
Removing reaction bounds when larger than the cobra-threshold of 1000.
FVA to identify blocked reactions and irreversibilities.
FVA(s) to identify essential reactions.
Preprocessing GPR rules (2897 genes, 8091 gpr rules).

**Comment by VonAlphaBisZulu** [comment]
Yes, this is - unfortunately - normal. The problem is that GPR rules are often extremely large. As an example, look at [ATPase from Recon3D](http://bigg.ucsd.edu/models/Recon3D/reactions/ATPS4mi). This reaction has plenty of genes associated with it and a GPR term with over to 600 disjuctions. For the computation of gene-KOs, all genes and GPR-terms need to be integrated in the stoichiometric network structure. In extreme cases this adds tens of thousands of metabolites and reactions. You can check how large the resulting model gets if you use the [standalone-GPR-integraton](https://straindesign.readthedocs.io/en/latest/examples/JN_08_compression.html#Standalone-GPR-integraton) on your model first. For Recon3D my network went up to 20,000 reactions and 10,000 metabolites and that can be too large for network compression and MILP construction.

You might be able to simplify or remove GPR terms that are irrelevant to your computation before going into strain design. For an example, take a look at the [genome scale strain design chapter](https://straindesign.readthedocs.io/en/latest/examples/JN_05_strain_design_mcs.html#Example-6:-Genome-scale-strain-designs-with-a-minimum-product-(1,4-butanediol)-yield-(SUCP-strain-design)).

**Comment by cjrodriguez98** [comment]
Thank you very much Philipp, I will try some of your advices. Thank you very much.

**Comment by cjavier98** [comment]
Thank you very much Phillipp. I will try some of your advices!
